var App = App || {};

Handlebars.registerHelper("inc", function(value, options)
{
    return parseInt(value) + 1;
});
Handlebars.registerHelper("selectCategory", function(category){
    if (category === 'history') {
        return 'Historia';
    } else if (category === 'entertainment') {
        return 'Entretenimiento';
    } else if (category === 'science') {
        return 'Ciencia y Tecnología';
    } else if (category === 'art') {
        return 'Arte y Literatura';
    } else {
        return 'Categoria no definida';
    }
})

App.templateManager = {
	templates: {},
	cachedTemplates: {},

	getCachedTemplate: function(tplName) {
		if (this.cachedTemplates.hasOwnProperty(tplName)) {
			return this.cachedTemplates[tplName];
		}
		if (this.templates.hasOwnProperty(tplName)) {
			this.cachedTemplates[tplName] = Handlebars.compile(this.templates[tplName]);
			return this.cachedTemplates[tplName];
		}

		throw 'The template ' + tplName + ' does not exist';
	}
};

App.templateManager.templates.navbar = [
    '<div class="container-fluid">',
    	'<div class="navbar navbar-default">',
    		'<div class="container-fluid">',
    			'<div class="navbar-header">',
    				'<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-content">',
    					'<span class="icon-bar"></span>',
    					'<span class="icon-bar"></span>',
    					'<span class="icon-bar"></span>',
    				'</button>',
    				'<a href="#index" class="navbar-brand">QUIZ</a>',
    			'</div>',
    			'<div class="collapse navbar-collapse" id="navbar-content">',
    				'<ul class="nav navbar-nav">',
    					'<li><a href="#index">Inicio</a></li>',
    					'<li><a href="#quiz">Quizes</a></li>',
    					'<li><a href="#ranking">Ranking</a></li>',
    					'{{#if user}}',
    						'<li class="dropdown" id="userDropdown">',
    							'<a class="userDropdownHandle" data-toggle="dropdown" data-target="eteve" href="eteve">',
    							'{{user}}<span class="caret"></span>',
    							'</a>',
    							'<ul class="dropdown-menu">',
    							'<li><a href="#profile">Perfil</a></li>',
    							'<li id="logout"><a href="#login">Cerrar Sesión</a></li>',
    							'</ul>',
    						'</li>',
    					'{{else}}',
    						'<li><a href="#login" class="btn btn-default">Log In</a></li>',
    					'{{/if}}',
    				'</ul>',
    			'</div>',
    		'</div>',
    	'</div>',
    '</div>',
    '<div id="sub-view"></div>'
].join('');

App.templateManager.templates.index = [
    '<div class="container">',
        '<div class="row text-center">',
            '<div id="welcome" class="col-sm-12 text-center">',
                '<div class="page-header">',
                    '<h1>Te damos la bienvenida <span>{{name}}</span></h1>',
                '</div>',
            '</div>',
            '<div class="col-xs-12">',
                '<h3>Aquí encontrarás...</h3>',
            '</div>',
            '<div class="col-xs-12 col-sm-6">',
                '<div class="well">',
                    '<h3>Quizes</h3>',
                    '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris posuere purus non nulla congue faucibus. Aliquam lobortis quam orci, in viverra libero suscipit eget. Integer tempor bibendum venenatis.</p>',
                    '<a href="#quiz" class="btn btn-primary">Saber más</a>',
                '</div>',
            '</div>',
            '<div class="col-xs-12 col-sm-6">',
                '<div class="well">',
                    '<h3>Rankings</h3>',
                    '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris posuere purus non nulla congue faucibus. Aliquam lobortis quam orci, in viverra libero suscipit eget. Integer tempor bibendum venenatis.</p>',
                    '<a href="#ranking" class="btn btn-primary">Saber más</a>',
                '</div>',
            '</div>',
        '</div>',
    '</div>'
].join('');

App.templateManager.templates.profile = [
    '<div class="container">',
    	'<div class="row">',
            '<div class="col-xs-12">',
                '<div class="page-header">',
                    '<h1>Perfil de {{user}}</h1>',
                '</div>',
            '</div>',
            '<div class="col-xs-12 col-sm-6">',
                '<h3>Tus Datos</h3>',
                '<table class="table">',
                    '<tbody>',
                        '<tr>',
                            '<td>Nombre:</td>',
                            '<td>{{name}}</td>',
                        '</tr>',
                        '<tr>',
                            '<td>Email:</td>',
                            '<td>{{email}}</td>',
                        '</tr>',
                        '<tr>',
                            '<td>Contraseña:</td>',
                            '<td>{{pass}}</td>',
                        '</tr>',
                    '</tbody>',
                '</table>',
                '<button type="button" class="btn btn-primary">Cambiar Datos</button>',
            '</div>',
            '<div class="col-xs-12 col-sm-6">',
                '<h3>Tu Puntaje</h3>',
                '<table class="table">',
                    '<tbody>',
                        '<tr>',
                            '<td>Historia:</td>',
                            '<td>{{scores.[0]}}</td>',
                        '</tr>',
                        '<tr>',
                            '<td>Entretenimiento:</td>',
                            '<td>{{scores.[1]}}</td>',
                        '</tr>',
                        '<tr>',
                            '<td>Ciencia y Tecnología:</td>',
                            '<td>{{scores.[2]}}</td>',
                        '</tr>',
                        '<tr>',
                            '<td>Arte y Literatura:</td>',
                            '<td>{{scores.[3]}}</td>',
                        '</tr>',
                    '</tbody>',
                '</table>',
            '</div>',
        '</div>',
    '</div>'
].join('');

App.templateManager.templates.quiz = [
    '<div class="container">',
    	'<div class="row">',
            '<div class="page-header col-xs-12 text-center">',
                '<h1>QUIZES</h1>',
            '</div>',
        '</div>',
        '<div class="row">',
            '<div class="col-xs-12 col-sm-3">',
                '<div class="thumbnail">',
                    '<a href="#game/history">',
                        '<div class="image-overlay">',
                            '<img class="image-target" src="img/historia.jpg">',
                            '<div class="overlay">',
                                '<p class="overlay-text"><span class="glyphicon glyphicon-play"></span></p>',
                            '</div>',
                        '</div>',
                    '</a>',
                    '<div class="caption">',
                        '<h3>Historia</h3>',
                        '<p>Lorem ipsum dolor sit amet, consectetur ...</p>',
                        '<p><a href="#game" class="btn btn-primary">Read More</a></p>',
                    '</div>',
                '</div>',
            '</div>',
            '<div class="col-xs-12 col-sm-3">',
                '<div class="thumbnail">',
                    '<a href="#game/entertainment">',
                        '<div class="image-overlay">',
                            '<img class="image-target" src="img/entretenimiento.png">',
                            '<div class="overlay">',
                                '<p class="overlay-text"><span class="glyphicon glyphicon-play"></span></p>',
                            '</div>',
                        '</div>',
                    '</a>',
                    '<div class="caption">',
                        '<h3>Entretenimiento</h3>',
                        '<p>Lorem ipsum dolor sit amet, consectetur ...</p>',
                        '<p><a href="#game" class="btn btn-primary">Read More</a></p>',
                    '</div>',
                '</div>',
            '</div>',
            '<div class="col-xs-12 col-sm-3">',
                '<div class="thumbnail">',
                    '<a href="#game/science">',
                        '<div class="image-overlay">',
                            '<img class="image-target" src="img/ciencia.jpg">',
                            '<div class="overlay">',
                                '<p class="overlay-text"><span class="glyphicon glyphicon-play"></span></p>',
                            '</div>',
                        '</div>',
                    '</a>',
                    '<div class="caption">',
                        '<h3>Ciencia y Tecnología</h3>',
                        '<p>Lorem ipsum dolor sit amet, consectetur ...</p>',
                        '<p><a href="#game" class="btn btn-primary">Read More</a></p>',
                    '</div>',
                '</div>',
            '</div>',
            '<div class="col-xs-12 col-sm-3">',
                '<div class="thumbnail">',
                    '<a href="#game/art">',
                        '<div class="image-overlay">',
                            '<img class="image-target" src="img/arte.jpg">',
                            '<div class="overlay">',
                                '<p class="overlay-text"><span class="glyphicon glyphicon-play"></span></p>',
                            '</div>',
                        '</div>',
                    '</a>',
                    '<div class="caption">',
                        '<h3>Arte y Literatura</h3>',
                        '<p>Lorem ipsum dolor sit amet, consectetur ...</p>',
                        '<p><a href="#game" class="btn btn-primary">Read More</a></p>',
                    '</div>',
                '</div>', 
            '</div>',
        '</div>',
    '</div>'
].join('');

App.templateManager.templates.loadError = [
    '<div class="container>',
        '<div class="row">',
            '<div class="col-xs-12 page-header text-center">',
                '<h1>Oops! Hubo un error al cargar las preguntas.</h1>',
                '<img src="img/marcianito.gif">',
            '</div>',
        '</div>',
    '</div>'
].join('');

App.templateManager.templates.game = [
    '<div class="container">',
    	'<div class="row">',
            '{{#if question}}',
            '<div class="col-xs-12 page-header text-center">',
                '<h1>{{selectCategory category}}</h1>',
            '</div>',
            '<div class="col-xs-6 text-center"><h4>Tiempo: <span id="time"></span></h4></div>',
            '<div class="col-xs-6 text-center"><h4>Puntos: <span id="points"></span></h4></div>',
            '<div class="col-xs-12 col-sm-8 col-sm-push-2 well pg text-center">',
                '<p>{{question}}</p>',
            '</div>',
            '<div class="col-xs-12 col-sm-6 col-sm-push-3">',
                '<div class="btn-options" style="margin-bottom:10px">',
                    '{{#each answers}}',
                    '<button id="{{@index}}" type="button" class="btn btn-default btn-block">{{this}}</button>',
                    '{{/each}}',
                '</div>',
            '</div>',
            '<div class="col-xs-12 col-sm-1 col-sm-push-3 text-center">',
                '<button id="next-btn" type="button" class="btn btn-default" disabled><span class="glyphicon glyphicon-chevron-right"></span></button>',
            '</div>',
    	    '{{else}}',
    	        '<div class="col-xs-12 page-header text-center">',
    	            '<h1>Puntaje</h1>',
    	        '</div>',
    	        '<div class="col-xs-12 text-center"><h1><span style="font-size:4em" id="points"></span></h1></div>',
    	        '<div class="col-xs-12 text-center">',
    	            '<p id="message"></p>',
    	            '<a href="#quiz" class="btn btn-primary">Continuar</a>',
    	        '</div>',
    	    '{{/if}}',
        '</div>',
    '</div>'
].join('');

App.templateManager.templates.ranking = [
    '<div class="container">',
    	'<div class="row">',
            '<div class="col-xs-12 text-center">',
                '<h1 class="page-header">RANKINGS</h1>',
            '</div>',
        '</div>',
        '<div class="row">',
            '<div class="col-xs-12 col-sm-8 col-sm-push-2">',
                '<div id="rankingSlider" class="carousel slide" data-ride="carousel">',
                    '<!--Indicators-->',
                    '<ol class="carousel-indicators">',
                        '<li data-target="#rankingSlider" data-slide-to="0" class="active"></li>',
                        '<li data-target="#rankingSlider" data-slide-to="1"></li>',
                        '<li data-target="#rankingSlider" data-slide-to="2"></li>',
                        '<li data-target="#rankingSlider" data-slide-to="3"></li>',
                    '</ol>',
                    '<!-- Wrapper for slides -->',
                    '<div class="carousel-inner">',
                        '<div class="item active">',
                            '<div>',
                                '<h4 style="text-align:center">Historia</h4>',
                                '<p style="text-align:center">Top 10 Scores:</p>',
                                '<table class="table">',
                                    '<thead>',
                                        '<tr>',
                                            '<th>#</th>',
                                            '<th>Usuario</th>',
                                            '<th>Puntaje</th>',
                                        '</tr>',
                                    '</thead>',
                                    '<tbody>',
                                        '{{#each history}}',
                                        '<tr>',
                                            '<td>{{inc @index}}</td>',
                                            '<td>{{attributes.user}}</td>',
                                            '<td>{{attributes.scores.[0]}}</td>',
                                        '</tr>',
                                        '{{/each}}',
                                    '</tbody>',
                                '</table>',
                            '</div>',
                        '</div>',
                        '<div class="item">',
                            '<div>',
                                '<h4 style="text-align:center">Entretenimiento</h4>',
                                '<p style="text-align:center">Top 10 Scores:</p>',
                                '<table class="table">',
                                    '<thead>',
                                        '<tr>',
                                            '<th>#</th>',
                                            '<th>Usuario</th>',
                                            '<th>Puntaje</th>',
                                        '</tr>',
                                    '</thead>',
                                    '<tbody>',
                                        '{{#each entertainment}}',
                                        '<tr>',
                                            '<td>{{inc @index}}</td>',
                                            '<td>{{attributes.user}}</td>',
                                            '<td>{{attributes.scores.[1]}}</td>',
                                        '</tr>',
                                        '{{/each}}',
                                    '</tbody>',
                                '</table>',
                            '</div>',
                        '</div>',
                        '<div class="item">',
                            '<div>',
                                '<h4 style="text-align:center">Ciencia y Tecnología</h4>',
                                '<p style="text-align:center">Top 10 Scores:</p>',
                                '<table class="table">',
                                    '<thead>',
                                        '<tr>',
                                            '<th>#</th>',
                                            '<th>Usuario</th>',
                                            '<th>Puntaje</th>',
                                        '</tr>',
                                    '</thead>',
                                    '<tbody>',
                                        '{{#each science}}',
                                        '<tr>',
                                            '<td>{{inc @index}}</td>',
                                            '<td>{{attributes.user}}</td>',
                                            '<td>{{attributes.scores.[2]}}</td>',
                                        '</tr>',
                                        '{{/each}}',
                                    '</tbody>',
                                '</table>',
                            '</div>',
                        '</div>',
                        '<div class="item">',
                            '<div>',
                                '<h4 style="text-align:center">Arte y Literatura</h4>',
                                '<p style="text-align:center">Top 10 Scores:</p>',
                                '<table class="table">',
                                    '<thead>',
                                        '<tr>',
                                            '<th>#</th>',
                                            '<th>Usuario</th>',
                                            '<th>Puntaje</th>',
                                        '</tr>',
                                    '</thead>',
                                    '<tbody>',
                                        '{{#each art}}',
                                        '<tr>',
                                            '<td>{{inc @index}}</td>',
                                            '<td>{{attributes.user}}</td>',
                                            '<td>{{attributes.scores.[3]}}</td>',
                                        '</tr>',
                                        '{{/each}}',
                                    '</tbody>',
                                '</table>',
                            '</div>',
                        '</div>',    
                    '</div>',
                '</div>',
            '</div>',
        '</div>',
    '</div>'
].join('');

App.templateManager.templates.login = [
    '<div class="container">',
    	'<div class="row">',
            '<div class="col-xs-12 text-center">',
                '<h1 class="page-header">Quiz Proyect</h1>',
            '</div>',
        '</div>',
        '<div class="row">',
            '<div class="col-xs-12 col-sm-6 col-sm-push-3">',
               '<ul class="nav nav-tabs">',
                    '<li class="active"><a href="#login-tab" data-toggle="tab">Iniciar Sesión</a></li>',
                    '<li><a href="#register-tab" data-toggle="tab">Registrarse</a></li>',
                '</ul>',
                '<div class="tab-content">',
                    '<div class="tab-pane active" id="login-tab">',
                        '<form class="form" id="login" name="login">',
                            '<div class="form-group">',
                                '<label for="userField">Usuario</label>',
                                '<input type="text" id="userField" name="userField" class="form-control" placeholder="Tu usuario" required>',
                            '</div>',
                            '<div class="form-group">',
                                '<label for="passwordField">Contraseña</label>',
                                '<input type="password" id="passwordField" name="passwordField" class="form-control" placeholder="Tu contraseña" required>',
                            '</div>',
                            '<button type="submit" class="btn btn-primary">Entrar</button>',
                            '<button type="reset" class="btn btn-default">Reiniciar</button>',
                        '</form>',
                    '</div>',
                    '<div class="tab-pane" id="register-tab">',
                        '<form class="form" id="register" name="register">',
                            '<div class="form-group">',
                                '<label for="userField">Nombre</label>',
                                '<input type="text" id="nameField" class="form-control" placeholder="Tu nombre" maxlength="15" required>',
                            '</div>',
                            '<div class="form-group">',
                                '<label for="fstNameField">Usuario</label>',
                                '<input type="text" id="userField" class="form-control" placeholder="Tu usuario" maxlength="10" required>',
                            '</div>',
                            '<div class="form-group">',
                                '<label for="emailField">Email</label>',
                                '<input type="email" id="emailField" class="form-control" placeholder="Tu correo" required>',
                            '</div>',
                            '<div class="form-group">',
                                '<label for="passwordField">Contraseña</label>',
                                '<input type="password" id="passwordField" class="form-control" placeholder="Tu contraseña" maxlength="50" required>',
                            '</div>',
                            '<button type="submit" class="btn btn-primary">Registrarse</button>',                            '<button type="reset" class="btn btn-default">Reiniciar</button>',
                        '</form>',
                    '</div>',
                '</div>',
            '</div>',
        '</div>',
    '</div>'
].join('');



